name: 'Build AUR Package'
branding:
  icon: user-check
  color: gray-dark
inputs:
  repo-name:
    description: 'AUR repository name to build'
    required: true
  preinstallPKGs:
    description: 'packages need install before build, separated by space'
    required: false
    default: ""
  local:
    description: 'build package with local PKGBUILD file'
    default: false
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-name }}
