name: BUILD

on:
  push:
    branches:
      - master
      - build
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [7-zip-full, anki, visual-studio-code-bin, wlr-randr-git,
                mpv-handler, wayfire, fcitx5-pinyin-custom-pinyin-dictionary,
                wps-office, hyprland-git, hyprland, tofi-git, waybar-hyprland-git,
                cliphist]
        include:
            - repos: wayfire
              localsource: "true"

      fail-fast: false
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
        preinstallPKGs: ${{ matrix.preinstall-pkgs }}
        localsource: ${{ matrix.localsource }}

    - uses: actions/upload-artifact@v3
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        if-no-files-found: error

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}

  uploadToOneDrive:      
    runs-on: ubuntu-latest
    if: always()
    needs: [buildAUR]

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
        id: download
      
      - uses: ./create-db-and-upload-action
        with:
          RCLONE_ONEDRIVE_CLIENT_ID: ${{ secrets.RCLONE_ONEDRIVE_CLIENT_ID }}
          RCLONE_ONEDRIVE_CLIENT_SECRET: ${{ secrets.RCLONE_ONEDRIVE_CLIENT_SECRET }}
          RCLONE_ONEDRIVE_REGION: global
          RCLONE_ONEDRIVE_TOKEN: ${{ secrets.RCLONE_ONEDRIVE_TOKEN }}
          RCLONE_ONEDRIVE_DRIVE_ID: ${{ secrets.RCLONE_ONEDRIVE_DRIVE_ID }}
          RCLONE_ONEDRIVE_DRIVE_TYPE: personal
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          dest_path: /Linux/Arch/repo
          repo_name: iflygo
          local_path: ${{ steps.download.outputs.download-path }}
