name: BUILD

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  buildAUR:
    strategy:
      matrix:
        repos:
          - visual-studio-code-bin
          - sway-git
          - zed-editor

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/cache@v4

      - uses: ./build-aur-action
        with:
          repo-name: ${{ matrix.repos }}

      - uses: actions/upload-artifact@v4
        with:
          path: ./*/*.pkg.tar.zst
          name: ${{ matrix.repos }}
          if-no-files-found: error
